name: Bug Report (RUS)
description: Сообщите о найденной проблеме
labels: ["bug"]
assignees: ["banan1442,mednoy"]
body:
  - type: markdown
    attributes:
      value: |
        Здравствуйте! Спасибо за сообщение об ошибке.
        
        Перед тем как сообщить об ошибке, пожалуйста, проверьте существующие задачи в этом репозитории — вы можете отфильтровать их по метке "bug" (проверьте также закрытые запросы).
        
  - type: input
    id: id
    attributes:
      label: Ваш Vatsim CID
      description: Это ваш логин Vatsim. Он нужен, чтобы мы могли связаться с вами в Discord, если вы там есть.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Версия сектора
      description: Укажите версию сектора — вы можете найти её в релизах.
      placeholder: Например, 0.1.1
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: Опишите вашу проблему
      description: Пожалуйста, расскажите, что происходит, какой ожидаемый результат и фактический. Если есть скриншоты или видео, прикрепите их!
    validations:
      required: true
  - type: textarea
    id: how
    attributes:
      label: Шаги воспроизведения
      description: Опишите, как можно воспроизвести проблему, даже если это очевидно. Если ваша проблема связана с конкретным диспетчером или пользователем, укажите их позывные и CID. Если проблему сложно воспроизвести, прикрепите видео.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Дополнительная информация
      description: Есть ли что-то, что нам нужно знать дополнительно? Расскажите!
    validations:
      required: false
