blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.com/invite/unnt
    about: ![Discord](https://cdn3.emoji.gg/emojis/5542-discord-clyde-gif.gif) Feel free to join our Discord to discuss stuff, including possible bugs and suggestions!
