blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.com/invite/unnt
    about: Feel free to join our Discord to discuss stuff, including possible bugs and suggestions!
