blank_issues_enabled: false
contact_links:
  - name: ![Discord](https://cdn3.emoji.gg/emojis/5542-discord-clyde-gif.gif)
    url: https://discord.com/invite/unnt
    about: Feel free to join our Discord to discuss stuff, including possible bugs and suggestions!
